islamic_quotes = [
    "Allah is enough for you.",
    "Patience is worship.",
    "The heart finds peace in remembering Allah.",
    "Allah never burdens a soul beyond what it can bear.",
    "Trust Allah even when life feels uncertain.",
    "A sincere dua can change destiny.",
    "Allah knows the pain inside your chest.",
    "Your Lord has not forgotten you.",
    "Allah sees every silent struggle.",
    "Prayer is peace for the soul.",
    "The believer always returns to Allah.",
    "Hardship is followed by ease.",
    "Allah’s mercy is endless.",
    "Do not lose hope in Allah.",
    "A patient heart is loved by Allah.",
    "Your sins are not bigger than Allah’s mercy.",
    "Allah can open doors nobody can close.",
    "Even delayed blessings are blessings.",
    "Stay close to Allah during hard times.",
    "The Quran heals hearts.",
    "Allah loves those who repent sincerely.",
    "Every hardship carries wisdom.",
    "Peace begins with trust in Allah.",
    "A believer grows through patience.",
    "Dua is never wasted.",
    "Allah hears what you cannot explain.",
    "The strongest hearts remember Allah often.",
    "Salah protects the heart.",
    "Allah can replace pain with peace.",
    "Do not let your sins distance you from Allah.",
    "Every test has purpose.",
    "Jannah is worth the struggle.",
    "A peaceful heart trusts Allah completely.",
    "Allah’s plan is always better.",
    "Keep making dua.",
    "Allah knows your intentions.",
    "A sincere heart is powerful.",
    "Allah rewards patience beautifully.",
    "Do not despair of Allah’s mercy.",
    "Faith grows during difficult moments.",
    "Allah sees your effort.",
    "Your tears are seen by Allah.",
    "Everything happens by Allah’s wisdom.",
    "Trust the timing of Allah.",
    "Allah can heal broken hearts.",
    "Keep your heart connected to Allah.",
    "The dunya is temporary.",
    "True success is pleasing Allah.",
    "Allah can change your life unexpectedly.",
    "Stay patient. Allah is with the patient.",
    "Allah’s light reaches every dark place.",
    "The best hearts remember Allah daily.",
    "Never underestimate the power of dua.",
    "Allah knows what your soul needs.",
    "Sabr brings beautiful rewards.",
    "A heart attached to Allah never breaks completely.",
    "Allah’s mercy is greater than every mistake.",
    "Every prayer brings you closer to peace.",
    "Allah understands unspoken pain.",
    "Faith makes the impossible possible.",
    "A believer finds strength in prayer.",
    "Allah can calm every storm inside you.",
    "The Quran is guidance for every heart.",
    "Patience today brings peace tomorrow.",
    "Allah’s promises are always true.",
    "Hope in Allah never disappoints.",
    "Allah loves those who trust Him.",
    "Even small duas are heard by Allah.",
    "Keep your soul clean with remembrance.",
    "Allah gives strength to tired hearts.",
    "A grateful heart receives more blessings.",
    "Allah can turn sadness into joy.",
    "Prayer strengthens the soul.",
    "Allah never ignores sincere tears.",
    "The remembrance of Allah softens the heart.",
    "Every delay has divine wisdom.",
    "Allah is near to the brokenhearted.",
    "Stay firm in faith during trials.",
    "Jannah is prepared for the patient.",
    "Allah sees what others cannot.",
    "Keep your faith stronger than your fears.",
    "Allah’s help arrives at the perfect time.",
    "A believer’s weapon is dua.",
    "Allah can change any situation instantly.",
    "True peace is found in Islam.",
    "Allah’s mercy surrounds the believers.",
    "Every hardship cleanses sins.",
    "The patient are rewarded without measure.",
    "Allah loves sincere repentance.",
    "Never stop asking Allah for guidance.",
    "Faith shines brightest during hardship.",
    "Allah can heal what nobody understands.",
    "Prayer is a conversation with Allah.",
    "Allah’s wisdom is beyond human understanding.",
    "The soul rests in remembering Allah.",
    "Every test brings hidden blessings.",
    "Allah writes the best stories.",
    "A believer trusts Allah in every condition.",
    "The beauty of Islam is mercy.",
    "Allah can open unexpected doors.",
    "Trust Allah even when answers are delayed.",
    "The strongest people rely on Allah.",
    "Allah rewards every sincere effort.",
    "Peace enters the heart through salah.",
    "Allah never abandons His servants.",
    "Hope is an act of worship.",
    "Allah sees the goodness in your heart.",
    "A sincere dua can move mountains.",
    "Allah’s love is endless.",
    "Every pain has meaning with Allah.",
    "Stay connected to the Quran.",
    "Allah gives relief after difficulty.",
    "A faithful heart stays calm in trials.",
    "Allah can replace every loss.",
    "Keep asking Allah for forgiveness.",
    "The patient hearts win in the end.",
    "Allah values sincerity over perfection.",
    "Every moment of patience is rewarded.",
    "Allah’s mercy reaches every sinner.",
    "Prayer brings clarity to the heart.",
    "Allah never wastes your tears.",
    "A believer finds comfort in dhikr.",
    "Trust Allah’s plan over your own.",
    "Allah strengthens weak hearts.",
    "The Quran is light for the soul.",
    "Allah loves humble hearts.",
    "Keep your intentions pure for Allah.",
    "Allah’s timing is always right.",
    "Faith is trusting Allah without seeing the outcome.",
    "Allah hears every whispered dua.",
    "The dunya fades but Allah remains.",
    "Allah gives peace to sincere hearts.",
    "A believer never loses hope.",
    "Allah’s forgiveness is limitless.",
    "Every prayer matters to Allah.",
    "Allah can guide any lost soul.",
    "Stay grateful in every season of life.",
    "Allah is closer than you think.",
    "The path to Jannah requires patience.",
    "Allah rewards hidden struggles.",
    "Never stop remembering Allah.",
    "Allah knows what is best for you.",
    "A heart filled with faith fears less.",
    "Allah can bring ease overnight.",
    "The believer rises after every fall.",
    "Allah’s mercy changes lives.",
    "Prayer protects the believer.",
    "Allah blesses those who stay patient.",
    "Every dua is answered in the best way.",
    "Allah sees your silent battles.",
    "A peaceful soul remembers Allah often.",
    "Allah can make impossible things happen.",
    "The best remedy is trust in Allah.",
    "Allah never fails His promises.",
]