mindset = [
    "Your mindset shapes your reality.",
    "Discipline is choosing what you want most over what you want now.",
    "Success starts with self-belief.",
    "Comfort zones destroy growth.",
    "Every master was once a beginner.",
    "Be stronger than your excuses.",
    "Difficult roads often lead to beautiful destinations.",
    "The pain of discipline is better than the pain of regret.",
    "Your only limit is your mind.",
    "Consistency beats talent when talent is lazy.",
    "Stop doubting yourself and start moving.",
    "Fear disappears when action begins.",
    "Progress matters more than perfection.",
    "Focus on becoming better, not showing off.",
    "Hard work compounds like interest.",
    "Your future depends on what you do today.",
    "One positive thought can change your whole day.",
    "Winners train, losers complain.",
    "A strong mindset creates strong results.",
    "You become what you repeatedly do.",
    "Don't wait for motivation, create discipline.",
    "Every setback is a lesson in disguise.",
    "Growth is uncomfortable because you've never been here before.",
    "The strongest people are built in hard times.",
    "Dream big but work bigger.",
    "Success is earned, not given.",
    "Your habits shape your future.",
    "Stay patient and trust your progress.",
    "Excuses sound best to the person making them.",
    "Small daily improvements create massive results.",
    "Your energy introduces you before you speak.",
    "Think positive, act positive, become positive.",
    "You are capable of more than you think.",
    "Train your mind to stay calm under pressure.",
    "Doubt kills more dreams than failure ever will.",
    "Discipline turns goals into achievements.",
    "Mindset is the foundation of success.",
    "Learn to rest, not quit.",
    "Success begins when excuses end.",
    "Strong minds create strong lives.",
    "Every day is a new opportunity to improve.",
    "The grind may be silent but the results will be loud.",
    "Keep showing up even on hard days.",
    "Your attitude determines your direction.",
    "Pressure creates diamonds.",
    "The version of you tomorrow depends on the effort today.",
    "You don't grow when life is easy.",
    "Stay hungry for improvement.",
    "Work hard in silence and let success speak.",
    "Mental toughness is built, not born.",
    "The harder you work, the luckier you become.",
    "Action cures fear.",
    "Your mindset can either imprison you or empower you.",
    "Discipline is self-respect in action.",
    "Never let temporary feelings make permanent decisions.",
    "Success is a series of small wins.",
    "You are one decision away from a different life.",
    "Confidence is built through preparation.",
    "Excuses delay greatness.",
    "If you get tired, learn to rest not quit.",
    "A focused mind is a powerful weapon.",
    "The strongest weapon against stress is your mindset.",
    "You don't have to be perfect to improve.",
    "Fall seven times, stand up eight.",
    "Strength grows in struggle.",
    "Your future self is watching you right now.",
    "Keep your vision bigger than your fears.",
    "Difficult moments reveal true character.",
    "Success requires sacrifice.",
    "Self-control is real power.",
    "A winner is just a loser who kept trying.",
    "The mind adapts to whatever you feed it.",
    "Positive thinking creates positive outcomes.",
    "Hard times create resilient people.",
    "Discipline is freedom.",
    "You either suffer the pain of discipline or regret.",
    "Growth begins when excuses end.",
    "Don't fear failure, fear staying the same.",
    "The comeback is always stronger than the setback.",
    "Push yourself because nobody else will do it for you.",
    "Success loves consistency.",
    "Your thoughts become your habits.",
    "Be patient with yourself but never lazy.",
    "Every challenge is preparing you for something greater.",
    "You were built to handle difficult moments.",
    "Train your mind to see opportunities.",
    "Success is built behind the scenes.",
    "The strongest version of you is still being created.",
    "Self-belief changes everything.",
    "A calm mind is a powerful mind.",
    "You don't need permission to improve your life.",
    "Hard work eventually outruns talent.",
    "One day or day one — you decide.",
    "Stay disciplined even when nobody is watching.",
    "Mental strength comes from overcoming struggles.",
    "You can restart as many times as necessary.",
    "Every day is a chance to become better.",
    "Your mindset determines your level.",
    "Success starts in the mind before it appears in reality.",
    "Believe in the process even when results are slow.",
    "Nothing changes until you change.",
    "Don't downgrade your dream to match your comfort zone.",
    "Focus on progress, not applause."
]